export const UserActionTypes = {
    REGISTER_USER: 'REGISTER_USER',
    LOGIN_LOCAL: 'LOGIN_LOCAL',
    LOGIN_THIRD_PARTY: 'LOGIN_THIRD_PARTY',
    LOGOUT_USER: 'LOGOUT_USER',
    SET_CURRENT_USER: 'SET_CURRENT_USER'
};